version: '3.8'

services:
  main:
    container_name: front
    build:
      context: .
    volumes: 
      - .:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    command: npm run start
    restart: always
