version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
    env_file: 
      - .env
    volumes: 
      - .:/backend
      - /backend/node_modules
    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on: 
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    env_file: 
      - .env
    environment: 
      PG_DATA: /var/lib/postgresql/data
    ports: 
      - 5432:53421
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes: 
  pgdata: